# Generated by Django 5.2.6 on 2025-10-17 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('state', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='cities/')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField()),
                ('long_description', models.TextField()),
                ('icon_path', models.CharField(blank=True, max_length=500)),
                ('features', models.JSONField(default=list)),
                ('benefits', models.JSONField(default=list)),
                ('process', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='lead',
            name='interest',
            field=models.CharField(choices=[('software_dev', 'Software Development Service'), ('website_dev', 'Website Development'), ('crm', 'CRM Solution'), ('hrms', 'HRMS Solution'), ('voip', 'VOIP Service'), ('api', 'API Development'), ('autodialer', 'Autodialer Solution'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('contact_form', 'Contact Form'), ('newsletter', 'Newsletter Signup'), ('download', 'Resource Download'), ('webinar', 'Webinar Registration'), ('demo', 'Demo Request'), ('city_page', 'City Page'), ('other', 'Other')], default='contact_form', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='core.city'),
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.city'),
        ),
        migrations.AddField(
            model_name='newslettersubscriber',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to='core.city'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='core.service'),
        ),
        migrations.AddField(
            model_name='lead',
            name='specific_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.service'),
        ),
        migrations.AddField(
            model_name='resourcedownload',
            name='related_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='core.service'),
        ),
        migrations.CreateModel(
            name='CityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_content', models.TextField(blank=True)),
                ('custom_features', models.JSONField(blank=True, default=list)),
                ('custom_benefits', models.JSONField(blank=True, default=list)),
                ('success_stories', models.JSONField(blank=True, default=list)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.city')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.service')),
            ],
            options={
                'verbose_name': 'City Service',
                'verbose_name_plural': 'City Services',
                'ordering': ['city__name', 'service__display_order'],
                'unique_together': {('city', 'service')},
            },
        ),
    ]
