# Generated by Django 5.2.6 on 2025-10-22 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_service_alter_lead_interest_alter_lead_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_bio',
            field=models.TextField(blank=True, help_text='Custom author bio for this post'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_description',
            field=models.TextField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reading_time',
            field=models.IntegerField(default=0, help_text='Estimated reading time in minutes'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='sections',
            field=models.JSONField(blank=True, default=list, help_text='Blog sections with headings, content, images, and more'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='table_of_contents',
            field=models.JSONField(blank=True, default=list, help_text='Auto-generated or custom table of contents'),
        ),
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('text', 'Text Content'), ('heading', 'Heading'), ('image', 'Image'), ('quote', 'Quote/Blockquote'), ('code', 'Code Block'), ('list', 'List'), ('video', 'Video Embed'), ('custom', 'Custom HTML')], default='text', max_length=20)),
                ('heading', models.CharField(blank=True, max_length=300)),
                ('heading_level', models.IntegerField(choices=[(2, 'H2'), (3, 'H3'), (4, 'H4')], default=2)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/sections/')),
                ('image_caption', models.CharField(blank=True, max_length=300)),
                ('video_url', models.URLField(blank=True)),
                ('code_language', models.CharField(blank=True, max_length=50)),
                ('list_items', models.JSONField(blank=True, default=list)),
                ('order', models.IntegerField(default=0)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_sections', to='core.blogpost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
