# Generated by Django 5.2.8 on 2025-11-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blogpost_author_bio_blogpost_author_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='interest',
            field=models.CharField(blank=True, choices=[('software_dev', 'Software Development Service'), ('website_dev', 'Website Development'), ('crm', 'CRM Solution'), ('hrms', 'HRMS Solution'), ('voip', 'VOIP Service'), ('api', 'API Development'), ('autodialer', 'Autodialer Solution'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
