# Generated by Django 5.2.8 on 2025-11-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_currency_service_price_alter_lead_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='plan1_features',
            field=models.JSONField(blank=True, default=list, help_text='List of features for Plan 1'),
        ),
        migrations.AddField(
            model_name='service',
            name='plan1_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='plan1_title',
            field=models.CharField(blank=True, default='Basic Plan', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='plan2_features',
            field=models.JSONField(blank=True, default=list, help_text='List of features for Plan 2'),
        ),
        migrations.AddField(
            model_name='service',
            name='plan2_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='plan2_title',
            field=models.CharField(blank=True, default='Standard Plan', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='plan3_features',
            field=models.JSONField(blank=True, default=list, help_text='List of features for Plan 3'),
        ),
        migrations.AddField(
            model_name='service',
            name='plan3_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='plan3_title',
            field=models.CharField(blank=True, default='Premium Plan', max_length=100),
        ),
    ]
